apiVersion: v1
kind: Pod
metadata:
  name: app-deployment
  labels:
    app: java
spec:
  containers: 
  - name: java
    image: my-java-app:latest
    imagePullPolicy: Never
    resources:
      limits:
        memory: "200Mi"